### ISSUE TITLE
Breaks choosewin plugin when cursor is on section header

### ISSUE THREAD

**Issue by raghur** [OXY2DEV/helpview.nvim#10]
this is really nice and a good QoL plugin but unfortunately, it seems to break the choosewin plugin's preview overlays on specific headings

https://github.com/user-attachments/assets/40a16761-abe6-4310-8c61-696a566ce860

The error shown is 
`choosewin: Vim(call): E867: (NFA) Unknown operator '\%-'`

**Comment by OXY2DEV** [comment]
That's an issue with `vim-choosewin`, not this plugin and I can already other similar plugins causing `vim-choosewin` to not work.

But it looks like that repository isn't being maintained anymore so you are most likely out of luck.

**Comment by OXY2DEV** [comment]
You may [find this plugin as an alternative](https://github.com/s1n7ax/nvim-window-picker) to `vim-choosewin`.
