### ISSUE TITLE
Feature request: OSC 8 hyperlink

### ISSUE THREAD

**Issue by wroyca** [OXY2DEV/helpview.nvim#3]
Hello o/

Thank you for this plugin! Something I think would be great to add is support for hyperlinks with mouse hover, similar to Emacs:

https://github.com/user-attachments/assets/5230166a-ad1d-4dcd-a55e-d328abfd9f82

This should be possible with, e.g. OSC 8

```code
printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'
```

https://github.com/user-attachments/assets/f054d32f-25c5-450f-8843-0a52f00d9879

**Comment by OXY2DEV** [comment]
Can't we already do that with tags?

https://github.com/user-attachments/assets/57cd1d6c-b035-4995-a5cc-25d9e630a8cf

Plus, I have never actually seen `hyperlinks` being used like that(as most of time they are too long to fit).

But if there are use cases then I guess I can add it.

**Comment by OXY2DEV** [comment]
I will have to see if it's possible inside neovim.

**Comment by wroyca** [comment]
> I will have to see if it's possible inside neovim.

Crude example:

![image](https://github.com/user-attachments/assets/3a1bfaf3-3e03-4452-a2e7-ea55fae251c3)

From https://neovim.io/doc/user/api.html#nvim_buf_set_extmark()

> url: A URL to associate with this extmark. In the TUI, the OSC 8 control sequence is used to generate a clickable hyperlink to this URL.

**Comment by OXY2DEV** [comment]
But `tags` don't really lead anywhere. So what URL should be used? 🤔

Vim just search all the `Tags` file to see where it is found.

**Comment by wroyca** [comment]
> But `tags` don't really lead anywhere. So what URL should be used? 🤔
> 
> > Using the file name will just open it in another editor window. But implantation would be difficult to say the least.
> 
> Vim just search all the `Tags` file to see where it is found.

Hm, perhaps empty? will have to investigate but so long as we have the "hyperlink" effect then it should be fine as the default behavior of clicking on the tag lead to said tag

**Comment by wroyca** [comment]
Some more fuzzing around:

https://github.com/user-attachments/assets/79e86b2e-3eb0-4b10-aadf-80b050330e15

**Comment by OXY2DEV** [comment]
What did you use for the `url`? In my case setting to "" doesn't seem to work.

**Comment by OXY2DEV** [comment]
I have also noticed that setting the url to " " does work but when terminals show the url preview it ends up showing " ".

**Comment by OXY2DEV** [comment]
I have also noticed that it doesn't quite work with `taglinks`.

**Comment by OXY2DEV** [comment]
![Screenshot_2024-08-12-20-59-45-939_com gaurav avnc-edit](https://github.com/user-attachments/assets/3863b7c7-f3b1-42ec-a1b3-8622ab49541f)


As you can see a hover window opens that shows the link. So, I don't think that approach will work.

**Comment by wroyca** [comment]
> ![Screenshot_2024-08-12-20-59-45-939_com gaurav avnc-edit](https://private-user-images.githubusercontent.com/122956967/357098947-3863b7c7-f3b1-42ec-a1b3-8622ab49541f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzUyMjcsIm5iZiI6MTcyMzQ3NDkyNywicGF0aCI6Ii8xMjI5NTY5NjcvMzU3MDk4OTQ3LTM4NjNiN2M3LWYzYjEtNDJlYy1hMWIzLTg2MjJhYjQ5NTQxZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxNTAyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTBjNThkZjRlMDE0NjM1ODVhMmRjY2M5ZjhhYjljNmRmNjRjMzBmNGMxYTYwMmEzYzBmMGYxNTFiOTI0NmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ppxSK8lxktT_DWMIEN_6gUd5Wssj98efi2SXoOFScd4)
> 
> As you can see a hover window opens that shows the link. So, I don't think that approach will work.

Curious, I don't have such hover window :thinking:

**Comment by OXY2DEV** [comment]
> > ![Screenshot_2024-08-12-20-59-45-939_com gaurav avnc-edit](https://private-user-images.githubusercontent.com/122956967/357098947-3863b7c7-f3b1-42ec-a1b3-8622ab49541f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzUyMjcsIm5iZiI6MTcyMzQ3NDkyNywicGF0aCI6Ii8xMjI5NTY5NjcvMzU3MDk4OTQ3LTM4NjNiN2M3LWYzYjEtNDJlYy1hMWIzLTg2MjJhYjQ5NTQxZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxNTAyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTBjNThkZjRlMDE0NjM1ODVhMmRjY2M5ZjhhYjljNmRmNjRjMzBmNGMxYTYwMmEzYzBmMGYxNTFiOTI0NmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ppxSK8lxktT_DWMIEN_6gUd5Wssj98efi2SXoOFScd4)
> > As you can see a hover window opens that shows the link. So, I don't think that approach will work.
> 
> Curious, I don't have such hover window 🤔

Yeah, it's a terminal thing. But that introduces a new issue. How exactly are we going to handle how links are shown? As you can see in my screenshot there is 2 lines instead of 1.

At the same time, not all terminals work the same so that could also be an issue.

**Comment by wroyca** [comment]
> > > ![Screenshot_2024-08-12-20-59-45-939_com gaurav avnc-edit](https://private-user-images.githubusercontent.com/122956967/357098947-3863b7c7-f3b1-42ec-a1b3-8622ab49541f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzUyMjcsIm5iZiI6MTcyMzQ3NDkyNywicGF0aCI6Ii8xMjI5NTY5NjcvMzU3MDk4OTQ3LTM4NjNiN2M3LWYzYjEtNDJlYy1hMWIzLTg2MjJhYjQ5NTQxZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxNTAyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTBjNThkZjRlMDE0NjM1ODVhMmRjY2M5ZjhhYjljNmRmNjRjMzBmNGMxYTYwMmEzYzBmMGYxNTFiOTI0NmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ppxSK8lxktT_DWMIEN_6gUd5Wssj98efi2SXoOFScd4)
> > > As you can see a hover window opens that shows the link. So, I don't think that approach will work.
> > 
> > 
> > Curious, I don't have such hover window 🤔
> 
> Yeah, it's a terminal thing. But that introduces a new issue. How exactly are we going to handle how links are shown? As you can see in my screenshot there is 2 lines instead of 1.

Nice timing, I was investigating it. Here's what I came up with (prototyping):

```lua
  local update_interval = 100 -- Time in milliseconds
  local function update_mouse_position ()
    local mouse_pos = vim.fn.getmousepos()
    local mouse_row = mouse_pos.line - 1
    local mouse_col = mouse_pos.column - 1

    if config_table.hl then
      if mouse_row == data.row_start and mouse_col >= data.col_start and mouse_col <= data.col_end then
        vim.api.nvim_buf_set_extmark(buffer, renderer.namespace, data.row_start, data.col_start, {
          virt_text_pos = "overlay",
          virt_text = {
            { data.text, renderer.set_hl(config_table.hl) },
          },
          hl_group = renderer.set_hl(config_table.hl),

          hl_mode = "combine",
          virt_text_hide = true,
          priority = 10,
          end_col = data.col_end,
          url = data.text
        })
      else
        vim.api.nvim_buf_set_extmark(buffer, renderer.namespace, data.row_start, data.col_start, {
          virt_text_pos = "overlay",
          virt_text = {
            { data.text, renderer.set_hl(config_table.hl) },
          },
          hl_group = renderer.set_hl(config_table.hl),

          hl_mode = "combine",
          virt_text_hide = true,
          priority = 10,
          end_col = data.col_end,
        })
      end
    end
    vim.defer_fn(update_mouse_position, update_interval)
  end
  vim.defer_fn(update_mouse_position, update_interval)
```

https://github.com/user-attachments/assets/c763b0a6-06e2-42c8-bad7-ff556b778dc7

**Comment by wroyca** [comment]
(small update, move the second extmark outside the mouse event loop)

```lua
renderer.component_renderer = function(buffer, data, config_table)
  if not config_table or config_table.enable == false then
    return
  end

  local conceal_before, conceal_after = config_table.conceal_before, config_table.conceal_after

  if config_table.conceal_before and pcall(config_table.conceal_before, data) then
    conceal_before = config_table.conceal_before(data)
  end

  if config_table.conceal_after and pcall(config_table.conceal_after, data) then
    conceal_after = config_table.conceal_after(data)
  end

  vim.api.nvim_buf_set_extmark(buffer, renderer.namespace, data.row_start, data.col_start, {
    virt_text_pos = "inline",
    virt_text = {
      { config_table.padding_left or "", renderer.set_hl(config_table.hl) },
      { config_table.icon or "", renderer.set_hl(config_table.hl) },
    },

    priority = 10,
    end_col = conceal_before and data.col_start + conceal_before or nil,
    conceal = conceal_before and "" or nil,
  })

  local update_interval = 100 -- Time in milliseconds
  local function update_mouse_position ()
    local mouse_pos = vim.fn.getmousepos()
    local mouse_row = mouse_pos.line - 1
    local mouse_col = mouse_pos.column - 1

    if config_table.hl then
      if mouse_row == data.row_start and mouse_col >= data.col_start and mouse_col <= data.col_end then
        vim.api.nvim_buf_set_extmark(buffer, renderer.namespace, data.row_start, data.col_start, {
          virt_text_pos = "overlay",
          virt_text = {
            { data.text, renderer.set_hl(config_table.hl) },
          },
          hl_group = renderer.set_hl(config_table.hl),

          hl_mode = "combine",
          virt_text_hide = true,
          priority = 10,
          end_col = data.col_end,
          url = data.text
        })
      end
    end
    vim.defer_fn(update_mouse_position, update_interval)
  end
  vim.defer_fn(update_mouse_position, update_interval)

  vim.api.nvim_buf_set_extmark(buffer, renderer.namespace, data.row_start, data.col_start, {
    virt_text_pos = "overlay",
    virt_text = {
      { data.text, renderer.set_hl(config_table.hl) },
    },
    hl_group = renderer.set_hl(config_table.hl),

    hl_mode = "combine",
    virt_text_hide = true,
    priority = 10,
    end_col = data.col_end,
  })

  vim.api.nvim_buf_set_extmark(buffer, renderer.namespace, data.row_start, data.col_end - (conceal_after or 0), {
    virt_text_pos = "inline",
    virt_text = {
      { config_table.padding_right or "", renderer.set_hl(config_table.hl) },
    },

    priority = 10,

    end_col = conceal_after and data.col_end or nil,
    conceal = conceal_after and "" or nil,
  })
end
```

**Comment by OXY2DEV** [comment]
Wouldn't this just lead to the same function running 100s of times per second?

> Because `renderer.render` would be called on various events add a new `defer_fn` every time.

**Comment by wroyca** [comment]
> Wouldn't this just lead to the same function running 100s of times per second?
> 
> > Because `renderer.render` would be called on various events adding a new `defer_fn` every time.

Yes, that's necessary to update `local mouse_pos = vim.fn.getmousepos()`, we need a event loop that is non-blocking, hence the defer_fn here

**Comment by OXY2DEV** [comment]
I think there's a simpler solution than this. I will see if it works or not.

**Comment by OXY2DEV** [comment]
Now, I have a new issue. How exactly do I ensure that this function isn't running on just any window?

**Comment by wroyca** [comment]
Crude example (don't mind prototyping flickering due to echo' loop)

```
  local update_interval = 100 -- Time in milliseconds
  local function update_mouse_position ()
    if vim.bo.filetype == "help" then
      print ("tracing")
      local mouse_pos = vim.fn.getmousepos()
      local mouse_row = mouse_pos.line - 1
      local mouse_col = mouse_pos.column - 1

      if config_table.hl then
        if mouse_row == data.row_start and mouse_col >= data.col_start and mouse_col <= data.col_end then
          vim.api.nvim_buf_set_extmark(buffer, renderer.namespace, data.row_start, data.col_start, {
            virt_text_pos = "overlay",
            virt_text = {
              { data.text, renderer.set_hl(config_table.hl) },
            },
            hl_group = renderer.set_hl(config_table.hl),

            hl_mode = "combine",
            virt_text_hide = true,
            priority = 10,
            end_col = data.col_end,
            url = data.text
          })
        end
      end
      vim.defer_fn(update_mouse_position, update_interval)
    end
  end
  vim.defer_fn(update_mouse_position, update_interval)
```

https://github.com/user-attachments/assets/40999302-ac4c-4e44-8971-3358b20cf750

**Comment by OXY2DEV** [comment]
Nevermind, I figured it out.

**Comment by OXY2DEV** [comment]
It appears that `vim.fn.getmousepos()` doesn't tell you which line the cursor currently is(unless you click).

So that approach wouldn't work. At the same time, constantly re-rendering just for the `mouse` isn't quite practical or performant.

**Comment by wroyca** [comment]
> It appears that `vim.fn.getmousepos()` doesn't tell you which line the cursor currently is(unless you click).
> 
> So that approach wouldn't work. At the same time, constantly re-rendering just for the `mouse` isn't quite practical or performant.

Note about https://neovim.io/doc/user/options.html#'mousemoveevent', we could probably hide behind this flag, making hyperlink opt-in. 

> constantly re-rendering just for the `mouse` isn't quite practical or performant

Agree, there's probably a better way to handle this stuffed somewhere in the doc and/or upstream discussion

**Comment by wroyca** [comment]
> It appears that vim.fn.getmousepos() doesn't tell you which line the cursor currently is(unless you click).

--- @class vim.fn.getmousepos.ret
--- @field screenrow integer
--- @field screencol integer
--- @field winid integer
--- @field winrow integer
--- @field wincol integer
--- @field line integer
--- @field column integer

With [mousemoveevent](https://neovim.io/doc/user/options.html#'mousemoveevent) 


https://github.com/user-attachments/assets/73c8f005-8cdf-4da7-968c-590e63f2bb36

**Comment by OXY2DEV** [comment]
![Screenshot_2024-08-12-22-15-29-001_com termux-edit](https://github.com/user-attachments/assets/dd6fb5ee-acef-47e4-8b89-7286201a4ffb)

> Setting this option can make pending mappings to be aborted when the mouse is moved.

Yeah, I don't think we should be changing it's value.

**Comment by wroyca** [comment]
Closing for now. I think Neovim is not quite there yet, and that there's a lot of hack and awkward workaround just to get subpar results. Was a interesting experiment though and may revisit at some point in the future. :)
