### ISSUE TITLE
error when I quit help files

### ISSUE THREAD

**Issue by Jaehaks** [OXY2DEV/helpview.nvim#8]
Thank you for your efforts, 

Whenever I quit opened help files, this mesage is invoked
![image](https://github.com/user-attachments/assets/2f379c74-8060-4f0a-9213-60d7d1ab49cd)

It said that it needs to set filetype, but the help file is already set to 'help'
What I am missing? 

this is my config
```lua
{
	-- rendering help using vimdoc treesitter
	"OXY2DEV/helpview.nvim",
	lazy = false, -- Recommended
	enabled = true,
	dependencies = {
		"nvim-treesitter/nvim-treesitter"
	}
}

```

**Comment by OXY2DEV** [comment]
That's strange. A help buffer shouldn't throw that error.

Did you do something like `:e <some-file>`(basically opening something on the buffer where the help file was being shown)?

**Comment by Jaehaks** [comment]
@OXY2DEV 

I got what is the problem. 
The error occurs whenever I close the help file with `:bd`.  not `:q`
If I disable `helpview.nvim`,  the `:bd` doesn't invoke error. so that is the reason why I think this way. 
It is same situation when I quit the help file after opening a `:e newfile` .
